### ISSUE TITLE
libcifpp-2.0.4 fails tests

### ISSUE THREAD

**Issue by pacho2** [PDB-REDO/libcifpp#12]
I get:
```
ctest -j 9 --test-load 999
Test project /var/tmp/portage/sci-libs/libcifpp-2.0.4/work/libcifpp-2.0.4_build
    Start 1: rename-compound-test
    Start 2: structure-test
    Start 3: unit-test
1/3 Test #1: rename-compound-test .............***Failed    0.00 sec
2/3 Test #2: structure-test ...................***Failed    0.16 sec
3/3 Test #3: unit-test ........................   Passed    0.22 sec

33% tests passed, 2 tests failed out of 3

Total Test time (real) =   0.23 sec

The following tests FAILED:
	  1 - rename-compound-test (Failed)
	  2 - structure-test (Failed)
Errors while running CTest
Output from these tests are in: /var/tmp/portage/sci-libs/libcifpp-2.0.4/work/libcifpp-2.0.4_build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```

Thanks a lot

**Comment by pacho2** [comment]
[LastTest.log](https://github.com/PDB-REDO/libcifpp/files/7589213/LastTest.log)

**Comment by mhekkel** [comment]
That's curious.

Just checked this:
git clone 
git checkout v2.0.4
mkdir build
cd build
cmake .. -DCIFPP_BUILD_TESTS=ON
cmake --build .
ctest .

And that works without a problem.

The log file you sent contains the error that indicates the file rsrc/pdbx_mmcif_v50.cif cannot be found. Did you build it somewhere else, some other directory perhaps?

**Comment by mhekkel** [comment]
oh wait.. yes you do.

OK, so I need to fix the make file to take care of this.

**Comment by mhekkel** [comment]
Should be fixed in trunk.

**Comment by pacho2** [comment]
Applying 
https://github.com/PDB-REDO/libcifpp/commit/2527aa5ea619c7022cbc03732df4e76d0ee90798.patch

Fixes structure-test but rename-compound-test keeps failing
```
ctest -j 9 --test-load 999
Test project /var/tmp/portage/sci-libs/libcifpp-2.0.4/work/libcifpp-2.0.4_build
    Start 1: rename-compound-test
    Start 2: structure-test
    Start 3: unit-test
1/3 Test #1: rename-compound-test .............***Failed    0.00 sec
2/3 Test #3: unit-test ........................   Passed    0.22 sec
3/3 Test #2: structure-test ...................   Passed    0.47 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =   0.47 sec

The following tests FAILED:
	  1 - rename-compound-test (Failed)
Errors while running CTest
Output from these tests are in: /var/tmp/portage/sci-libs/libcifpp-2.0.4/work/libcifpp-2.0.4_build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
[LastTest.log](https://github.com/PDB-REDO/libcifpp/files/7597078/LastTest.log)

**Comment by mhekkel** [comment]
Well, that was at least one failed test less than where we started with. ;-)

I've checked in another change, could you please try again?

**Comment by pacho2** [comment]
Where can I find that commit? Is it in a different branch than trunk?

Thanks

**Comment by mhekkel** [comment]
It is this commit: https://github.com/PDB-REDO/libcifpp/commit/2b6f1bd9ee656a8c13a948b2b7fcc3b41736a1b9

That is in trunk. It is a rather trivial change and before adding a version tag to it I'd like to know if this solves the problem you are seeing.

**Comment by pacho2** [comment]
I tried it too, but keeps failing :(
```
ctest -j 9 --test-load 999
Test project /var/tmp/portage/sci-libs/libcifpp-2.0.4/work/libcifpp-2.0.4_build
    Start 1: rename-compound-test
    Start 2: structure-test
    Start 3: unit-test
1/3 Test #1: rename-compound-test .............***Failed    0.00 sec
2/3 Test #3: unit-test ........................   Passed    0.25 sec
3/3 Test #2: structure-test ...................   Passed    0.53 sec

67% tests passed, 1 tests failed out of 3

Total Test time (real) =   0.54 sec

The following tests FAILED:
	  1 - rename-compound-test (Failed)
Errors while running CTest
Output from these tests are in: /var/tmp/portage/sci-libs/libcifpp-2.0.4/work/libcifpp-2.0.4_build/Testing/Temporary/LastTest.log
Use "--rerun-failed --output-on-failure" to re-run the failed cases verbosely.
```
[LastTest.log](https://github.com/PDB-REDO/libcifpp/files/7603223/LastTest.log)

**Comment by mhekkel** [comment]
The log file contains:
Error loading dictionary "/var/tmp/portage/sci-libs/libcifpp-2.0.4/work/libcifpp-2.0.4/test/REA.cif"

Does that file exist? And is it readable by the build proces?

**Comment by mhekkel** [comment]
Ah, found it. You are not using resources, obviously. And you did not have a previous libcifpp installed.

This problem should now be fixed. Really.

**Comment by pacho2** [comment]
It works perfectly indeed :D

Thanks a lot!
