### ISSUE TITLE
Possible missing include in CifUtils.cpp

### ISSUE THREAD

**Issue by jamaliki** [PDB-REDO/libcifpp#13]
I believe std::setprecision requires the <iomanip> header file https://en.cppreference.com/w/cpp/io/manip/setprecision. 
I got the following error trying to compile this file:

local/libcifpp/src/CifUtils.cpp:699:28: error: ‘setprecision’ is not a member of ‘std’
   os << std::fixed << std::setprecision(1) << ss << 's';

And adding this header fixed it.

**Comment by mhekkel** [comment]
Could you please let me know what compiler you are using?

**Comment by jamaliki** [comment]
g++ 8.2

**Comment by mhekkel** [comment]
Added #include <iomanip> to CifUtils.cpp so this should be fixed now. Tested with gcc 8.4, but that should be similar to 8.2
