### ISSUE TITLE
error

### ISSUE THREAD

**Issue by onlyonewater** [PDB-REDO/libcifpp#14]
when I run `cmake --build . --config Release`, an error has shown`libcifpp/include/cif++/Cif++.hpp:35:20: fatal error: optional: No such file or directory`, what's wrong?

**Comment by mhekkel** [comment]
You must have a very old C++ compiler if the standard optional header file is not available. Please upgrade your compiler, in case you use GCC I'd recommend to use at least version 9. clang version 10 or higher is also an option.

**Comment by onlyonewater** [comment]
when I use gcc 9.5, an error has shown `In file included from libcifpp/src/AtomType.cpp:30:0:
libcifpp/include/cif++/Cif++.hpp:35:20: fatal error: optional: No such file or directory
compilation terminated.`

**Comment by onlyonewater** [comment]
and clang must be needed?
