### ISSUE TITLE
Include error

### ISSUE THREAD

**Issue by gemapatricia** [PDB-REDO/libcifpp#16]
Hello everyone,

I have just integrated your library into our software (Xmipp) and I am trying to replicate the `example.cpp` file for our code. The include I use is `#include "libcifpp/include/cif++/Cif++.hpp"`, which is the equivalent of `#include <cif++/Cif++.hpp>` in the original `example.cpp`, but when I try to compile it, it throws the following error:
```
In the included library/data/pdb.cpp:41 file:
../libcifpp/include/cif++/Cif++.hpp:44:10: fatal error: cif++/CifUtils.hpp: No such file or directory
   #include "cif++/CifUtils.hpp"
            ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

So the line of code that rises the error is in the file `libcifpp/include/cif++/Cif++.hpp`, matching the line 44, `#include "cif++/CifUtils.hpp"`, which seems strange to us. Do you know any reason for this or do you have any suggestion?

Looking forward to your response, thanks a lot.

**Comment by mhekkel** [comment]
Are you trying to build the example.cpp file that comes with libcifpp? 
The makefile in the example assumes you've installed libcifpp in a system wide location (e.g. /usr/local). But the default these days is in $HOME/.local. Perhaps you even installed it elsewhere. Anyway, if you now run `pkg-config --cflags libcifpp` it should print out  something containing `-I/home/maarten/.local/include`. (I installed libcifpp in my .local directory).

Now, if your pkg-config does not find libcifpp you either have to install it in e.g. /usr/local or you should specify the PKG_CONFIG_PATH in the environment.

First see if you can get pkg-config to locate libcifpp:

`PKG_CONFIG_PATH=~/.local/lib/pkgconfig/ pkg-config --cflags libcifpp`

And if that works, run make like this:

`PKG_CONFIG_PATH=~/.local/lib/pkgconfig/ make`

Hope this helps.

**Comment by gemapatricia** [comment]
No, I basically copied the code inside the main method of the file `example.cpp` into our software (Xmipp), so I am compiling my code, instead of the file that you provide as part of the library.
In our case, all libraries are stored in this path `~/scipion3/xmipp-bundle/src/`. We have tried to include it in the Xmipp environment like this `PKG_CONFIG_PATH=~/scipion3/xmipp-bundle/src/`, without success. Could you specify which environment you are referring to?
Thanks for your advice.

**Comment by mhekkel** [comment]
If you type:

`pkg-config PKG_CONFIG_PATH=~/scipion3/xmipp-bundle/src/ --cflags libcifpp`

Do you then get any output? If so, you should use that output when calling the compiler that compiles your code.

So, in my case e.g., if I run pkg-config like this:

`$ PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig pkg-config --cflags libcifpp`

It will reply with `-pthread -I/home/maarten/.local/include`

So I then have to call g++ with _-pthread -I/home/maarten/.local/include_

**Comment by gemapatricia** [comment]
We found out what was causing the problem. If the include is `#include <cif++/CifUtils.hpp>` instead of `#include "cif++/CifUtils.hpp"`, there are no compilation errors. Could you modify it? Because if we so do, any update in the library will bring back this issue.

**Comment by mhekkel** [comment]
Fixed, thanks for the feedback.
