### ISSUE TITLE
Unable to build with VS2019 

### ISSUE THREAD

**Issue by kirillv** [PDB-REDO/libcifpp#21]
First of all thnx for code sharing!

Tried to build this library on windows but faced some issues.

template <typename T>
using selected_charconv = typename std::conditional_t<std::experimental::is_detected_v<from_chars_function, T>, std_charconv<T>, my_charconv<T>>;

this code from text.hpp is not valid, because VS2019 (even 2022) experimental has no is_detected_v<...> defined.

#include <experimental/type_traits> - there is no such a file in VS SDK, And is_detected_v should be there.

Also there is some problems to config project with cmake. Cmake cant find gxrio - even if im putting path to it in cmake-gui. I hacked cmake to bypass it (putting hardcoded path to cmake var) and generate sln.

Thnx in advance!

**Comment by mhekkel** [comment]
The trunk now contains code I managed to compile with MSVC 2019. I will make a release for it as soon as I've updated and tested all depending software as well.
