### ISSUE TITLE
.conf file should be installed into $DESTDIR$PREFIX/etc

### ISSUE THREAD

**Issue by yurivict** [PDB-REDO/libcifpp#23]
[here](https://github.com/PDB-REDO/libcifpp/blob/trunk/CMakeLists.txt#L449)

-- $PREFIX is missing.

**Comment by mhekkel** [comment]
Could you please be a bit more verbose? Or propose a patch?

**Comment by mhekkel** [comment]
Ah, you mean, $PREFIX might be either /, /usr or /usr/local, right?

**Comment by yurivict** [comment]
```
@@ -444,11 +444,11 @@ if(CIFPP_INSTALL_UPDATE_SCRIPT)
        install(DIRECTORY DESTINATION "$ENV{DESTDIR}/etc/libcifpp/cache-update.d")
 
        # a config to, to make it complete
-       if(NOT EXISTS "$ENV{DESTDIR}/etc/libcifpp.conf")
+       if(NOT EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/etc/libcifpp.conf")
                file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/libcifpp.conf [[# Uncomment the next line to enable automatic updates
 # update=true
 ]])
-               install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libcifpp.conf DESTINATION "$ENV{DESTDIR}/etc")
+               install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libcifpp.conf DESTINATION "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/etc")
                install(CODE "message(\"A configuration file has been written to $ENV{DESTDIR}/etc/libcifpp.conf, please edit this file to enable automatic updates\")")
        endif()
```

And reading of this file should also be corrected accordingly in the C++ code.

**Comment by mhekkel** [comment]
I wish it was that simple. Your suggestion breaks installation in Linux since the directory then ends up to be /usr/etc.

Besides, the update script is installed in a Linux specific location, for FreeBSD a file in /.../periodic/weekly is required.

**Comment by yurivict** [comment]
You should use ```install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libcifpp.conf DESTINATION etc)``` to install, like any other files. Not sure why do you have DESTDIR there,

**Comment by mhekkel** [comment]
OK, should be fixed now. FYI: cmake handles DESTDIR automatically. And you don't have to mess with CMAKE_INSTALL_PREFIX, just use e.g. CMAKE_INSTALL_FULL_SYSCONFDIR to get the actual and correct /etc directory.

I also updated the 'cron' script to fetch updated dictionary files. It is installed in /usr/local/etc/periodic/weekly for non Linux OS's. Hope that will cover everything. Note that in a clean installation, the update will not run automatically, you have to edit /usr/local/etc/libcifpp.conf first.
