### ISSUE TITLE
libcifpp not installing in R through install_github

### ISSUE THREAD

**Issue by Mira2121** [PDB-REDO/libcifpp#26]
Hi, 
When I'm trying to install_github "PDB-REDO/libcifpp" through R (by first installing and calling 'library(devtools)') in linux, the following is the error that I'm getting. I've also tried via 'githubinstall("libcifpp")', alas "libcifpp" is not available in the list. This is a prerequisite that I need before installing PDB-REDO/dssp. Need help please? 
> install_github("PDB-REDO/libcifpp")
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

**Comment by mhekkel** [comment]
This is not an issue with libcifpp but with the package manager you're trying to use. May I suggest to install DSSP and libcifpp using the suggestions in the readme documents of both?
