### ISSUE TITLE
ctest -C Release error @ cbaakman 

### ISSUE THREAD

**Issue by K-kiran90** [PDB-REDO/libcifpp#27]
[sudo] password for kiran: 
Test project /home/kiran/Downloads/libcifpp-trunk_1/libcifpp-trunk/build
No tests were found!!!

For DSSP4 I'm installing libcif++

**Comment by mhekkel** [comment]
To enable test, you have to specify ENABLE_TESTING during the configure step.
As in:

cmake .. -DENABLE_TESTING=ON

**Comment by K-kiran90** [comment]
Please let me know how to install DSSP4 as I am getting many errors, need
to run around 800 pdbids for RC plot for phi and psi.

Very hard to install as many errors whilce cmake itself . Link followed for
DSSP4 https://github.com/PDB-REDO/dssp
