### ISSUE TITLE
Issue while reading 6m0j.pdb

### ISSUE THREAD

**Issue by Comeylo** [PDB-REDO/libcifpp#28]
Dear @mhekkel,

I am attempting to integrate libcifpp within the SBL (sbl.inria.fr), initially to allow for reading .mmcif files, and ultimately to replace our current algorithmic reading .pdb files.

While I did not encounter any specific issue regarding mmcif files, I just stumbled across a problem reading 6m0j.pdb.

Assertion failed: (d != 0), function operator(), file pdb2cif.cpp, line 5564.

Could you please let me know if you have a moment to dedicate to fixing this case ? Is this file too malformed to be considered valid ?

Côme

**Comment by mhekkel** [comment]
Interesting. Apparently you are using a debug build of libcifpp. That's good while developing software of course.

The assert you've hit is more or less a debugging help that should perhaps have been cleaned up before releasing. As far as I can see it does no harm, it only seems to indicate some input error.

Which brings me to the real question here, where did you get this PDB file from? I tried reproducing your error with the one from the PDB itself (pdb6m0j.ent) and that one does not stumble over the assert.

-maarten

**Comment by Comeylo** [comment]
https://files.rcsb.org/download/6M0J.pdb

Regarding the compilation mode, I had not realized it was compiled in Debug mode before your comment.
I compiled and uploaded a libcifpp package on conda for the osx-arm64 platform matching  (edit : approximately, there was a dandling "-" character in the cmake command) the recipe used for the linux build (https://anaconda.org/search?q=libcifpp for a view on the two packages).
The size of the packages beeing roughly the same, I assumed both are of same type -> which is misleading size the size of the package is mostly the components.cif file..

Please give me some time to investigate the compilation mode of both libcifpp conda packages.

**Comment by drlemmus** [comment]
Please note that the conda package was made by a third party. We are happy to help as much as we can but we cannot vouch for its quality.

**Comment by Comeylo** [comment]
So, after a quick look and some changes to the conda recipe, I have updated the sbl conda channel with an actual Release compiled library (for osx-arm64 atm, other builds should follow) of libcifpp.

I am not yet confident as why the current bioconda recipe doesn't produce a Release compiled library (for osx-arm64 at least), need to investigate (i.e., I am not familiar with the syntax they use).

As you foresaw, I get the same behavior for pdb and cif version of the aforementioned file.

Time to thank you for the effort put into developing this library (and actually others at which I am looking lately dssp port notably).

This issue can be closed on my side, up to you to handle the assertion as you wish.
