### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by martin-s-a** [PDB-REDO/libcifpp#35]
I have spent the last two days trying to figure out a memory leak I had in my code when using this library. Since the project I was working on has a pretty large code base, it took me a looooong time to find out that the memory leak was actually being caused by this library.
To prove it, I have written a small c++ file with a main function and an auxiliary one. The code is the following:
```
void readCIF(const std::string &fnCIF, cif::datablock &dataBlock)
{
    cif::file cifFile;
    cifFile.load(fnCIF);
    dataBlock = cifFile.front();
}

int main() {
    std::filesystem::path filePath = "/home/msalinas/Documents/standalone-installations/cifParser/libcifpp/examples/1cbs.cif.gz";
    cif::datablock dataBlock;
    readCIF(filePath, dataBlock);
    return 0;
}
```
This, returns the following in valgrind:
```
LEAK SUMMARY:
==207784==    definitely lost: 2,544 bytes in 53 blocks
==207784==    indirectly lost: 61,624 bytes in 1,888 blocks
==207784==      possibly lost: 0 bytes in 0 blocks
==207784==    still reachable: 0 bytes in 0 blocks
==207784==         suppressed: 0 bytes in 0 blocks
==207784== 
==207784== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
```
If I remove the `dataBlock = cifFile.front();`, the leak is gone.
If I create a new empty `datablock` object and assign it like that:
```
void readCIF(const std::string &fnCIF, cif::datablock &dataBlock)
{
    cif::file cifFile;
    cifFile.load(fnCIF);
    cif::datablock db;
    dataBlock = db;
}
```
the leak is also gone (but then I'm not reading anything from the file, so that is pointless).
If I write the `.front()` return into `db` but not assign it back to `dataBlock`, also no leak (but then I'm losing the contents of the file as the `readCIF()` function exits):
```
void readCIF(const std::string &fnCIF, cif::datablock &dataBlock)
{
    cif::file cifFile;
    cifFile.load(fnCIF);
    cif::datablock &db = cifFile.front();
    //dataBlock = db;
}
```
But if I uncomment the last line an store the file contents into `dataBlock`, then I'm losing memory.
The leak only shows up when the contents of the cif file are stored inside a pointer received by argument, that's why I didn't do it all in the `main()` function and used another one instead.
My guess is that there has to be a problem with memory management in the `cif::datablock` class. I'm not fluent enough in c++ to try fixing it myself, but at least I was able to identify this issue so it could (hopefully) get fixed @mhekkel :)

**Comment by mhekkel** [comment]
Found it, thanks for reporting.

Fix is in trunk.
