### ISSUE TITLE
Installation issues with libcifpp for dssp

### ISSUE THREAD

**Issue by MohammadAliAmir** [PDB-REDO/libcifpp#38]
Hi,

I am trying to install libcifpp to install DSSP to work with bio3d. In the README of DSSP, it was clear to me that I need libcifpp and libmcfp.
When I try to install libcifpp, cmake builds the target but eventually quits on an error 
```
make[2]: Leaving directory `/gpfs/gssgpfs1/biogrid/tools/eb/build/libcifpp/5.0.8/GCCcore-10.2.0/easybuild_obj'
[100%] Built target cifpp
make[1]: Leaving directory `/gpfs/gssgpfs1/biogrid/tools/eb/build/libcifpp/5.0.8/GCCcore-10.2.0/easybuild_obj'
make: *** [all] Error 2
```
Im using GCCcore 10.2.0 as opposed to the 9.3.0 used in the development of libcifpp.

**Comment by mhekkel** [comment]
You've sent only a small part of the output, making it difficult to 
diagnose what goes wrong.

Did you try a cmake --install? And if so, did you either specify a 
destination directory using CMAKE_INSTALL_PREFIX, or did you run the 
install step as root? If you did not one of these, you might have run 
into permission problems trying to install into /usr/local.

Op 11-04-2023 om 15:08 schreef MohammadAliAmir:

**Comment by MohammadAliAmir** [comment]
I am installing this through easybuild, so everything is done through an easybuild user. 
The log file of the easybuild run is in the attachment.

[libciff_log.txt](https://github.com/PDB-REDO/libcifpp/files/11250483/libciff_log.txt)

However, as I have a workaround to install dssp, I would not mind if you agree to close the ticket.
