### ISSUE TITLE
Support for gcc < 10

### ISSUE THREAD

**Issue by martin-s-a** [PDB-REDO/libcifpp#39]
I've found this problem on setups with gcc 8 and gcc 9:
```
Scanning dependencies of target cifpp
[  4%] Building CXX object CMakeFiles/cifpp.dir/src/category.cpp.o
/home/agarcia/scipion3/xmipp-bundle/src/libcifpp/src/category.cpp: In member function ‘cif::condition cif::category::get_children_condition(cif::row_handle, const cif::category&) const’:
/home/agarcia/scipion3/xmipp-bundle/src/libcifpp/src/category.cpp:1052:73: error: ‘cif::iset’ {aka ‘class std::set<std::__cxx11::basic_string<char>, cif::iless>’} has no member named ‘contains’
    else if (link->m_parent_keys.size() > 1 and not mandatoryChildFields.contains(childKey))
                                                                         ^~~~~~~~
gmake[2]: *** [CMakeFiles/cifpp.dir/build.make:82: CMakeFiles/cifpp.dir/src/category.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:114: CMakeFiles/cifpp.dir/all] Error 2
gmake: *** [Makefile:171: all] Error 2
 Cannot build dependencies
Traceback (most recent call last):
  File "/home/agarcia/anaconda3/envs/scipion3/bin/emprogram", line 8, in <module>
    sys.exit(main())
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/cmd/program.py", line 43, in main
    runProgram(program, params)
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pwem/utils.py", line 73, in runProgram
    pwutils.runJob(None, program, params, env=env)
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 55, in runJob
    return runCommand(command, env, cwd)
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 70, in runCommand
    check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
  File "/home/agarcia/anaconda3/envs/scipion3/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command ' ./xmipp ' returned non-zero exit status 1.
```

This happens because `std::set` does not include method `contains()` until C++20, which forces users to have at least gcc 10.
It should be easily avoided changing this line:
`else if (link->m_parent_keys.size() > 1 and not mandatoryChildFields.contains(childKey))`
with this:
`else if (link->m_parent_keys.size() > 1 and mandatoryChildFields.find(childKey) == mandatoryChildFields.end())`
and should not cause any issues with newer versions.

I understand it is important to migrate to new versions of programmig languages and use the features they provide, so that's why I think it could be useful pushing this change to a different branch rather than `trunk`, so anyone who needs this support can have it cloning that specific branch.

Do you think it could be possible?
Thanks!

Edit: trying to implement those changes in my fork, i have realised that an additional change is needed.
In `condition.cpp`, line 70, it is necessary to replace this line:
```c++
c.key_field_indices().contains(m_item_ix) and
```
Edit 2: For that change, the whole if needs to be restructured like this:
```c++
if (c.get_cat_validator() != nullptr and
	c.key_field_indices().size() == 1)
{
	const auto field_keys = c.key_field_indices();
	if (field_keys.find(m_item_ix) != field_keys.end()) {
		m_single_hit = c[{ { m_item_tag, m_value } }];
	}
}
```
So the indices share a same set and the comparison is done properly.

With those two changes, I was able to compile and use the library using gcc 8.4.0.

**Comment by mhekkel** [comment]
Although I appreciate your efforts, the code in libcifpp is moving fast into a direction that will be very hard to compile with older compilers. I think the minimal requirement of gcc 9.4 is not that much to ask for.

If it was for me, I'd be using a lot more of c++20 features already, or even c++23.

**Comment by martin-s-a** [comment]
I totally understand, that's why i talked about a separate branch that is not trunk, which might or might not get feature updates in the future.
I developed that changes I said [in a fork I created](https://github.com/MartinSalinas98/libcifpp/tree/ms_feature_ciflibrary), feel free to check that out if you want to.

**Comment by marcom** [comment]
@MartinSalinas98 Thank you very much for the supplied patches! They helped fix the build with clang++-13 when using the LLVM libc++. See https://github.com/JuliaPackaging/Yggdrasil/pull/6977 for the details.
