### ISSUE TITLE
error while generating components.cif file

### ISSUE THREAD

**Issue by mashu94** [PDB-REDO/libcifpp#42]
I'm installing it as per given instructions. after using the command "cmake --build build" I've got an error at the last step. I'am attatching screenshot of my terminal.

![Screenshot from 2023-06-02 13-01-07](https://github.com/PDB-REDO/libcifpp/assets/58736557/c554ccdd-6628-4a36-b4f6-a4ab00aa81cc)

**Comment by mhekkel** [comment]
Apparently, downloading the components.cif.gz file failed. Try deleting that file and run the build step again. A new file should be downloaded automatically.

**Comment by mashu94** [comment]
I tried. It didnt work. 

For reference, I'll attach the screenshot of the previous command "cmake -S . -B build -DCMAKE_INSTALL_PREFIX=$HOME/.local -DCMAKE_BUILD_TYPE=Release".
![Screenshot from 2023-06-02 14-31-05](https://github.com/PDB-REDO/libcifpp/assets/58736557/d6ccfed5-0612-4bf9-8af7-94b8505cd7eb)

**Comment by mashu94** [comment]
so i manually downloaded the components.cif.gz file and placed it data/ directory and it worked
