### ISSUE TITLE
Installation from source

### ISSUE THREAD

**Issue by gcroci2** [PDB-REDO/libcifpp#49]
I am trying to install DSSP from source on Snellius (Red Hat Enterprise Linux 8.6, GCC 8.5.0). As in the readme, I tried first to install [libcifpp](https://github.com/PDB-REDO/libcifpp), which requires [mrc](https://github.com/mhekkel/mrc). But mrc tries to install libcifpp itself, and this causes a circular dependency issue. The installation of mrc fails because I don't have libcifpp, and I can't install libcifpp, and thus dssp.

**Comment by mhekkel** [comment]
Are you sure? mrc should not have any dependency on libcifpp.

**Comment by mhekkel** [comment]
Since building the code with gcc 8.5 may prove to be a challenge, you might be better of using the pre built executables you can download from https://github.com/PDB-REDO/dssp/releases/tag/v4.4.0

**Comment by gcroci2** [comment]
I am sorry, I misread the names of the packages. DSSP requires `libcifpp` (or `libcif++`), which in turns requires `mrc` (which requires `libmcfp`). When I try to clone mrc repo, I get this error:
```bash
Cloning into '/gpfs/home1/ccrocion/repositories/mrc/libmcfp'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mhekkel/libmcfp.git' into submodule path '/gpfs/home1/ccrocion/repositories/mrc/libmcfp' failed
Failed to clone 'libmcfp'. Retry scheduled
Cloning into '/gpfs/home1/ccrocion/repositories/mrc/libmcfp'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mhekkel/libmcfp.git' into submodule path '/gpfs/home1/ccrocion/repositories/mrc/libmcfp' failed
Failed to clone 'libmcfp' a second time, aborting
```

I tried launching from the Snellius terminal the mkdssp-4.4.0.exe that I downloaded in my home dir, but it gave me a "Permission denied" error.

**Comment by mhekkel** [comment]
Ah, I see the problem. There was an incorrect url for a submodule in mrc.

But since you're about to install dssp anyway, may I suggest to install [libmcfp](https://github.com/mhekkel/libmcfp) yourself instead of using a submodule in mrc. You'll need it for dssp as well.

The mrc repository has been updated so this error will not occur again. Thanks for reporting this problem.

**Comment by mhekkel** [comment]
> I tried launching from the Snellius terminal the mkdssp-4.4.0.exe that I downloaded in my home dir, but it gave me a "Permission denied" error.

That is easy to solve. First you need to download the correct executable, an .exe is for Windows, you need the one name 
mkdssp-4.4.0-linux-x64 

And then, after downloading, you may have to mark the file as an executable, like this:

```console
chmod a+x mkdssp-4.4.0-linux-x64 
```

**Comment by gcroci2** [comment]
> > I tried launching from the Snellius terminal the mkdssp-4.4.0.exe that I downloaded in my home dir, but it gave me a "Permission denied" error.
> 
> That is easy to solve. First you need to download the correct executable, an .exe is for Windows, you need the one name mkdssp-4.4.0-linux-x64
> 
> And then, after downloading, you may have to mark the file as an executable, like this:
> 
> ```
> chmod a+x mkdssp-4.4.0-linux-x64 
> ```

That works, and then if I launch the file from the terminal I see `mkdssp` helper. How can I make this visible to all my home folders?
Also, biopython still looks for `dssp`, and I still get errors about not finding dssp when I run my python tests.

**Comment by drlemmus** [comment]
Did you tell it to look for mkdssp? https://biopython.org/docs/latest/api/Bio.PDB.DSSP.html?highlight=dssp#module-Bio.PDB.DSSP

Note that the documentation still assumes DSSP version 3.

**Comment by gcroci2** [comment]
> Did you tell it to look for mkdssp? https://biopython.org/docs/latest/api/Bio.PDB.DSSP.html?highlight=dssp#module-Bio.PDB.DSSP
> 
> Note that the documentation still assumes DSSP version 3.

yes, but I have only the file marked as executable in my home folder, and the python environment can't find it. How can I add it for example to my PATH as `mkdssp`?

**Comment by drlemmus** [comment]
The python way to add things to your PATH is described here: https://www.johnny-lin.com/cdat_tips/tips_pylang/path.html That said, I'm not a python user.
