### ISSUE TITLE
build error `constexpr variable 'kGoldenRatio' must be initialized by a constant expression`

### ISSUE THREAD

**Issue by dsclassen** [PDB-REDO/libcifpp#51]
I'm trying to build this on a Mac with
cmake version 3.27.6
Apple clang version 15.0.0 (clang-1500.0.40.1)

I get this error about 34% of the way through the build procedure:

```
libcifpp/include/cif++/point.hpp:886:4: error: constexpr variable 'kGoldenRatio' must be initialized by a constant expression
```

**Comment by mhekkel** [comment]
You can change constexpr with simply const and recompile the code.

I've changed that in trunk.

Thanks for reporting
