### ISSUE TITLE
README.md ccmake typos

### ISSUE THREAD

**Issue by alphataubio** [PDB-REDO/libcifpp#53]
in README.md, shouldnt it be cmake instead of ccmake ?

**Comment by mhekkel** [comment]
ccmake is the GUI version of cmake, it presents a 'graphical' user interface where you can review settings and then generate the makefiles that are used with `cmake --build build`.

On windows, ccmake can be replaced with cmake-gui.exe.

But you're right, maybe I should explain that more clearly in the Readme.
