### ISSUE TITLE
cif::pdb::read std::_Nested_exception<std::runtime_error>

### ISSUE THREAD

**Issue by biohegedus** [PDB-REDO/libcifpp#55]
Hi,

I built libcifpp from source.
I tried to test with a simple code:

```
int main(int argc, char *argv[])
{
  if (argc != 2) {
    std::cerr << "you should provide a file" << std::endl;
    exit(1);
  }

    // Read file, can be PDB or mmCIF and can even be compressed with gzip.
    std::cerr << "Loading..." << std::endl;
    cif::file file = cif::pdb::read(argv[1]);
    std::cerr << "done" << std::endl;
```

If I run ./test 2BBO.cif or ./test 2BBO.pdb I got:
```
Loading...
Error parsing PDB at line 2
terminate called after throwing an instance of 'std::_Nested_exception<std::runtime_error>'
  what():  Error reading file 2BBO.pdb
Aborted
```

```
Loading...
terminate called after throwing an instance of 'std::_Nested_exception<std::runtime_error>'
  what():  Error reading file 2BBO.cif
Aborted
```

Thanks for your help, 
Tamas

**Comment by biohegedus** [comment]
If I build dssp with the compiled libcifpp, I got this:

```
mkdssp 2BBO.pdb 
Error parsing PDB at line 2
2BBO does not match rx for id: Success

```

But no output, no success.

**Comment by mhekkel** [comment]
Could you please share the first line of the PDB file you're trying to read?

**Comment by biohegedus** [comment]
https://www.rcsb.org/structure/2BBO
```
HEADER    TRANSPORT PROTEIN                       17-OCT-05   2BBO              
TITLE     HUMAN NBD1 WITH PHE508                                          
```

But it also fails on the corresponding cif file.

**Comment by mhekkel** [comment]
That's very curious. I copied your code and ran it on my machine with a fresh copy of libcifpp and it ran like it should:

```console
./test-libcifpp 2bbo.pdb
Loading...
done
```

So, the question is, what OS are you using? And what is the compiler you use?

BTW, wrapping the calls to cif++ code in a try/catch block will at least capture the error message. Look at the dssp code to see how nested exceptions can be written properly (see the void print_what function in mkdssp.cpp)

**Comment by biohegedus** [comment]
Debian 11
g++ (Debian 10.2.1-6) 10.2.1 20210110

If I insert a try catch with print_what:
```
Error parsing PDB at line 2
Error reading file 2BBO.pdb
 >> 2BBO does not match rx for id: Success
```
Error reading file is strange. 2BBO.pdb is in the same folder and readable.

**Comment by mhekkel** [comment]
The error comes from the mmCIF validating software. Maybe the file mmcif_pdbx.dic is corrupt? This file is a so-called resource, see the documentation on where it is located:

https://www.hekkelman.net/libcifpp-doc/resources.html

You could try to see if replacing that file helps.

One more question, did you install mrc?

**Comment by biohegedus** [comment]
ls /opt/libcifpp/share/libcifpp/
components.cif  mmcif_ddl.dic  mmcif_ma.dic  mmcif_pdbx.dic

export LIBCIFPP_DATA_DIR=/opt/libcifpp/share/libcifpp

I get the same error.
I did not install mrc.

**Comment by mhekkel** [comment]
I still don't get this. The problem is a regular expression coming from the mmcif_pdbx file that does not match the string 2BBO. This means that only one remaining thing may be wrong, and that's the regular expression library used. Did you install a private version of libboost?

**Comment by biohegedus** [comment]
I have libboost installed. However, I do not understand "a private version"...
libboost1.74-dev, libboost1.74-tools-dev and other libboost libraries (apt, debian)

**Comment by mhekkel** [comment]
Well, people tend to install a version of boost from source code instead of using the one provided by the OS.

But this should not be a problem, since you are building from the source code fetched from github, right?

One more question, are you using debian on a regular PC with amd64 CPU? If you don't know, please post the output from uname -a here.

**Comment by biohegedus** [comment]
I pulled the source from the github yesterday.
No, not on a very regular PC. But not HPC.
Linux myhost 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux
AMD EPYC 7371 16-Core Processor

**Comment by mhekkel** [comment]
So you tried building your own dssp and that failed. Could you please try to download the linux executable from our github release page here: https://github.com/PDB-REDO/dssp/releases/tag/v4.4.0

Does that give the same output, or does that one work correctly?

**Comment by biohegedus** [comment]
The linux executable works correctly.

**Comment by mhekkel** [comment]
Hmm, ok. That rules out a lot of things.

What remains is the question why your self-compiled code gives an error. Could you please try with another compiler, e.g. with clang++. You can install that using apt-get.

To specify the compiler to use with cmake, use the following:

```console
cd <your libcifpp source dir>
rm -rf build
cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++
cmake --build build
```

And then run the tests:

```console
ctest --test-dir build
```

**Comment by biohegedus** [comment]
You may know this warning 
libcifpp/src/pdb/reconstruct.cpp:520:23: warning: inequality comparison result unused [-Wunused-comparison]
                        row["type_symbol"] != parent["type_symbol"].text();


ctest --test-dir build | tee out.ctest
Test project /home/hegedus/sysadm/src/libcifpp
No tests were found!!!

**Comment by mhekkel** [comment]
OK, sorry, no tests are enabled by default. Try this instead:

```console
cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTING=ON
```

and then the rest

**Comment by biohegedus** [comment]
rm -fR build/
cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DBUILD_TESTING=ON
cmake --build build
ctest --test-dir build
Test project /home/hegedus/sysadm/src/libcifpp
No tests were found!!!

**Comment by mhekkel** [comment]
OK, fixed that warning, was a stupid error

> You may know this warning libcifpp/src/pdb/reconstruct.cpp:520:23: warning: inequality comparison result unused [-Wunused-comparison] row["type_symbol"] != parent["type_symbol"].text();

But back to the core issue.

Lets try one more thing, could you please rerun the steps above (including removing the build directory) and then run the actual  build with an extra flag:

```console
cmake --build build --verbose
```

And then copy the complete output of all steps here. Oh, and please send me the file build/CMakeCache.txt as well.

**Comment by biohegedus** [comment]
Pls find them attached.
[build.zip](https://github.com/PDB-REDO/libcifpp/files/14463941/build.zip)

**Comment by mhekkel** [comment]
Looking at the output I see that the tests are created. So, maybe it is the version of cmake that does not recognize the command for ctest.

You can try:

```console
cd build
ctest
```

or run the executables manually, but that requires you know where and how to run them. For most it is as simple as:

```console
cd test
../build/test/unit-v2-test
```

**Comment by biohegedus** [comment]
./unit-v2-test 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Attempt to add a file resource for mmcif_pdbx.dic that cannot be used (/home/hegedus/sysadm/src/libcifpp/build/test/../rsrc/mmcif_pdbx.dic) :Success
Aborted

**Comment by mhekkel** [comment]
I ran into a similar problem when building on Windows recently and changed the error checking lines. I think this might have fixed the issue you see as well. But I would appreciate it very much if you could please check this?

**Comment by biohegedus** [comment]
This was in the stdout:
CMake Error at CMakeLists.txt:467 (install):
   install TARGETS given unknown argument "FILE_SET".

See the cmakeerror.log attached.
[CMakeError.log](https://github.com/PDB-REDO/libcifpp/files/14596791/CMakeError.log)

**Comment by mhekkel** [comment]
Well, I should have set the minimum required version for cmake to version 3.23. Anyway, this is not going to end well since the version of debian you are using is too old. You should upgrade your system, as of debian 12 you can simply do `apt-get install libcifpp-dev` and have a working version of cif++.
