### ISSUE TITLE
missing headers, when including cifpp

### ISSUE THREAD

**Issue by cbaakman** [PDB-REDO/libcifpp#56]
cifpp version: v7.0.1

After building and installing libcifpp, I include the headers.
However, I get errors like:
```
/usr/local/include/cif++/utilities.hpp:29:10: fatal error: cif++/exports.hpp: No such file or directory
/usr/local/include/cif++/item.hpp:31:10: fatal error: cif++/text.hpp: No such file or directory
/usr/local/include/cif++.hpp:32:10: fatal error: cif++/format.hpp: No such file or directory
/usr/local/include/cif++/symmetry.hpp:30:10: fatal error: cif++/matrix.hpp: No such file or directory
/usr/local/include/cif++.hpp:41:10: fatal error: cif++/gzio.hpp: No such file or directory
```

After copying the files manually, the issue is solved. However, I wonder why the installer doesn't do this.

**Comment by mhekkel** [comment]
The cmake file was changed to use file_set headers instead of manually install all header files. But I forgot to add exports to this file_set. This is fixed now in version 7.0.3.

Thanks for reporting
