### ISSUE TITLE
/usr/local/etc/libcifpp.conf is only installed when the file isn't present, even when installation is done into a stage directory

### ISSUE THREAD

**Issue by yurivict** [PDB-REDO/libcifpp#58]
```/usr/local/etc/libcifpp.conf``` is the final destination for the config file.
When the installation is done into a stage directory (using the DESTDIR environment variable), the file is only installed when the file ```/usr/local/etc/libcifpp.conf``` isn't present.

It should check the file presence in the installation destination ```$DESTDIR/usr/local/etc/libcifpp.conf```, not in the ```/usr/local/etc/libcifpp.conf``` location which isn't where installing is done.

**Comment by mhekkel** [comment]
OK, I see what you mean.

Could you do me a favor? I've checked in a version that might solve this issue (and many related). It is in the **develop** branch. I do not know how you create the packages for FreeBSD so I don't know how to test whether what I did is correct. Could you please test this for me?
