### ISSUE TITLE
Configure error: issue with extracting .gz file

### ISSUE THREAD

**Issue by JiaGengChang** [PDB-REDO/libcifpp#6]
Description of the issue:
Ran into error when following build instructions provided in README.md.
Specifically the step `cmake ..`

Error message:
```
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
CMake Error: Problem with archive_read_open_file(): Unrecognized archive format
CMake Error at CMakeLists.txt:257 (file):
  file failed to extract:
  /cluster/gjb_lab/2472402/Projects/libcifpp/data/components.cif.gz


-- Configuring incomplete, errors occurred!
See also "/cluster/gjb_lab/2472402/Projects/libcifpp/build/CMakeFiles/CMakeOutput.log".
See also "/cluster/gjb_lab/2472402/Projects/libcifpp/build/CMakeFiles/CMakeError.log".
```

The file can be unpacked with gunzip. I tried it manually.

**Comment by JiaGengChang** [comment]
I have attached the log files below
[CMakeOutput.log](https://github.com/PDB-REDO/libcifpp/files/7100704/CMakeOutput.log)
[CMakeError.log](https://github.com/PDB-REDO/libcifpp/files/7100706/CMakeError.log)

**Comment by mhekkel** [comment]
Could you please let me know what version of cmake you're using? Is that 3.21?

**Comment by JiaGengChang** [comment]
Yes indeed! 
```
(build-env) [2472402@login2 2472402]$ cmake --version
cmake version 3.21.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
(build-env) [2472402@login2 2472402]$
```

P.S. the error goes away after manually extracting the file and re-running the command

**Comment by mhekkel** [comment]
I've dropped the extraction lines, the makefile now uses gunzip always. Should fix this issue.
